setTimeout(function() {
  $('.msg-box1').fadeTo('slow', 1);
}, 2000);
setTimeout(function() {
  $('.msg-box').fadeTo('slow', 1);
}, 3500);
setTimeout(function() {
  $('.msg-box3').fadeTo('slow', 1);
}, 5000);
setTimeout(function() {
  $('.msg-box4').fadeTo('slow', 1);
}, 6000);
setTimeout(function() {
  $('.msg-box5').fadeTo('slow', 1);
}, 8000);
